#!/bin/bash
 
NAME="bekindred_app"                                  # Name of the application
DJANGODIR=/webapps/bekindred/beKindred.com/bekindred  # Django project directory
SOCKFILE=/webapps/bekindred/run/gunicorn.sock         # we will communicte using this unix socket
USER=bekindred                                        # the user to run as
GROUP=bekindred                                       # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=bekindred.settings.production_linode             # which settings file should Django use
DJANGO_WSGI_MODULE=bekindred.wsgi                     # WSGI module name
 
echo "Starting $NAME as `whoami`"
 
# Activate the virtual environment
cd $DJANGODIR
source ../../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /webapps/bekindred/bin/gunicorn ${DJANGO_WSGI_MODULE} \
  --pythonpath $PYTHONPATH \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=127.0.0.1:8000 \
  --log-level=debug \
  --log-file=-
